#include "net/entity_protocol.hpp"
#include <cmath>
#include <cstring>
namespace kraken::net { namespace {
void u16(Byte* d,std::uint16_t v){d[0]=Byte(v);d[1]=Byte(v>>8);} std::uint16_t g16(const Byte*d){return std::uint16_t(std::uint8_t(d[0]))|std::uint16_t(std::uint8_t(d[1]))<<8;}
void u32(Byte*d,std::uint32_t v){for(int i=0;i<4;++i)d[i]=Byte(v>>(8*i));} std::uint32_t g32(const Byte*d){std::uint32_t v=0;for(int i=0;i<4;++i)v|=std::uint32_t(std::uint8_t(d[i]))<<(8*i);return v;}
void f(Byte*d,float v){std::uint32_t b;std::memcpy(&b,&v,4);u32(d,b);} float gf(const Byte*d){auto b=g32(d);float v;std::memcpy(&v,&b,4);return v;}
bool finite(float v){return std::isfinite(v);} EntityCodecError valid(const EntitySpawn&s){if(!s.entity_id)return EntityCodecError::InvalidEntity;if(!s.generation)return EntityCodecError::InvalidGeneration;if(!is_valid_entity_kind(s.kind))return EntityCodecError::InvalidKind;const float* v=&s.position.x;for(int i=0;i<3;++i)if(!finite(v[i]))return EntityCodecError::NonFiniteValue; const float*q=&s.rotation.x;float n=0;for(int i=0;i<4;++i){if(!finite(q[i]))return EntityCodecError::NonFiniteValue;n+=q[i]*q[i];}if(std::abs(n-1)>0.01f)return EntityCodecError::InvalidQuaternion;if(!finite(s.health_fraction)||s.health_fraction<0||s.health_fraction>1)return EntityCodecError::InvalidHealth;return EntityCodecError::None;}
}
EntityCodecError encode_entity_spawn(const EntitySpawn&s,MutableByteView o)noexcept{if(o.size()<kEntitySpawnWireSize)return EntityCodecError::OutputTooSmall;auto e=valid(s);if(!entity_codec_succeeded(e))return e;auto*d=o.data();u32(d,kEntitySpawnWireMagic);u16(d+4,1);d[6]=Byte(s.kind);d[7]=Byte{};u32(d+8,s.entity_id);u16(d+12,s.generation);u16(d+14,0);u32(d+16,s.prototype_id);u32(d+20,s.owner_entity_id);u32(d+24,std::uint32_t(s.belong));f(d+28,s.position.x);f(d+32,s.position.y);f(d+36,s.position.z);f(d+40,s.rotation.x);f(d+44,s.rotation.y);f(d+48,s.rotation.z);f(d+52,s.rotation.w);f(d+56,s.health_fraction);u32(d+60,0);u32(d+64,0);return e;}
EntityCodecError decode_entity_spawn(ByteView i,EntitySpawn&o)noexcept{if(i.size()!=kEntitySpawnWireSize)return EntityCodecError::InputSizeMismatch;auto*d=i.data();if(g32(d)!=kEntitySpawnWireMagic)return EntityCodecError::BadMagic;if(g16(d+4)!=1)return EntityCodecError::BadVersion;if(std::uint8_t(d[7])||g16(d+14)||g32(d+60)||g32(d+64))return EntityCodecError::BadFlags;EntitySpawn s{};s.kind=EntityKind(std::uint8_t(d[6]));s.entity_id=g32(d+8);s.generation=g16(d+12);s.prototype_id=g32(d+16);s.owner_entity_id=g32(d+20);s.belong=std::int32_t(g32(d+24));s.position={gf(d+28),gf(d+32),gf(d+36)};s.rotation={gf(d+40),gf(d+44),gf(d+48),gf(d+52)};s.health_fraction=gf(d+56);auto e=valid(s);if(entity_codec_succeeded(e))o=s;return e;}
EntityCodecError encode_entity_despawn(const EntityDespawn&s,MutableByteView o)noexcept{if(o.size()<kEntityDespawnWireSize)return EntityCodecError::OutputTooSmall;if(!s.entity_id)return EntityCodecError::InvalidEntity;if(!s.generation)return EntityCodecError::InvalidGeneration;auto*d=o.data();u32(d,kEntityDespawnWireMagic);u16(d+4,1);d[6]=Byte(s.reason);d[7]=Byte{};u32(d+8,s.entity_id);u16(d+12,s.generation);u16(d+14,0);return EntityCodecError::None;}
EntityCodecError decode_entity_despawn(ByteView i,EntityDespawn&o)noexcept{if(i.size()!=kEntityDespawnWireSize)return EntityCodecError::InputSizeMismatch;auto*d=i.data();if(g32(d)!=kEntityDespawnWireMagic)return EntityCodecError::BadMagic;if(g16(d+4)!=1)return EntityCodecError::BadVersion;if(std::uint8_t(d[7])||g16(d+14))return EntityCodecError::BadFlags;EntityDespawn s{g32(d+8),g16(d+12),std::uint8_t(d[6])};if(!s.entity_id)return EntityCodecError::InvalidEntity;if(!s.generation)return EntityCodecError::InvalidGeneration;o=s;return EntityCodecError::None;}
}
