#include "net/input_command.hpp"
#include <bit>
#include <cmath>
namespace kraken::net { namespace {
void u16(Byte*d,std::uint16_t v)noexcept{d[0]=static_cast<Byte>(v);d[1]=static_cast<Byte>(v>>8);}void u32(Byte*d,std::uint32_t v)noexcept{for(int i=0;i<4;++i)d[i]=static_cast<Byte>(v>>(8*i));}std::uint16_t r16(const Byte*d)noexcept{return static_cast<std::uint16_t>(static_cast<std::uint8_t>(d[0]))|(static_cast<std::uint16_t>(static_cast<std::uint8_t>(d[1]))<<8);}std::uint32_t r32(const Byte*d)noexcept{std::uint32_t v=0;for(int i=0;i<4;++i)v|=static_cast<std::uint32_t>(static_cast<std::uint8_t>(d[i]))<<(8*i);return v;}void f32(Byte*d,float v)noexcept{u32(d,std::bit_cast<std::uint32_t>(v));}float rf32(const Byte*d)noexcept{return std::bit_cast<float>(r32(d));}
InputCommandCodecError valid(const InputCommand&c)noexcept{if(!c.entity_id)return InputCommandCodecError::InvalidEntityId;if(!std::isfinite(c.throttle)||!std::isfinite(c.steer)||!std::isfinite(c.brake))return InputCommandCodecError::NonFiniteValue;if(c.throttle<-1||c.throttle>1||c.brake<0||c.brake>1||c.steer<-3.141593f||c.steer>3.141593f)return InputCommandCodecError::ValueOutOfRange;return InputCommandCodecError::None;}}
InputCommandCodecError encode_input_command(const InputCommand&c,MutableByteView o)noexcept{if(o.size()<kInputCommandWireSize)return InputCommandCodecError::OutputTooSmall;auto e=valid(c);if(!input_command_codec_succeeded(e))return e;Byte*d=o.data();u32(d,kInputCommandWireMagic);u16(d+4,kInputCommandWireVersion);u16(d+6,0);u32(d+8,c.entity_id);u32(d+12,c.sequence);u32(d+16,c.client_tick);f32(d+20,c.throttle);f32(d+24,c.steer);f32(d+28,c.brake);d[32]=static_cast<Byte>(c.handbrake);d[33]=static_cast<Byte>(c.request_unstuck);d[34]=static_cast<Byte>(c.horn);d[35]=Byte{};return InputCommandCodecError::None;}
InputCommandCodecError decode_input_command(ByteView i,InputCommand&c)noexcept{if(i.size()!=kInputCommandWireSize)return InputCommandCodecError::InputSizeMismatch;const Byte*d=i.data();if(r32(d)!=kInputCommandWireMagic)return InputCommandCodecError::BadMagic;if(r16(d+4)!=kInputCommandWireVersion)return InputCommandCodecError::BadVersion;if(r16(d+6)||d[35]!=Byte{})return InputCommandCodecError::BadFlags;if(d[32]!=Byte{}&&d[32]!=static_cast<Byte>(1))return InputCommandCodecError::InvalidHandbrake;if(d[33]!=Byte{}&&d[33]!=static_cast<Byte>(1))return InputCommandCodecError::InvalidUnstuckRequest;if(d[34]!=Byte{}&&d[34]!=static_cast<Byte>(1))return InputCommandCodecError::InvalidHorn;InputCommand v{r32(d+8),r32(d+12),r32(d+16),rf32(d+20),rf32(d+24),rf32(d+28),d[32]==static_cast<Byte>(1),d[33]==static_cast<Byte>(1),d[34]==static_cast<Byte>(1)};auto e=valid(v);if(!input_command_codec_succeeded(e))return e;c=v;return e;}
}
