#include "net/loot_transaction.hpp"

namespace kraken::net { namespace {
void put16(Byte* d, std::uint16_t v) noexcept { d[0]=static_cast<Byte>(v); d[1]=static_cast<Byte>(v>>8); }
void put32(Byte* d, std::uint32_t v) noexcept { for(int i=0;i<4;++i)d[i]=static_cast<Byte>(v>>(8*i)); }
std::uint16_t get16(const Byte* d) noexcept { return static_cast<std::uint16_t>(static_cast<std::uint8_t>(d[0]))|(static_cast<std::uint16_t>(static_cast<std::uint8_t>(d[1]))<<8); }
std::uint32_t get32(const Byte* d) noexcept { std::uint32_t v=0;for(int i=0;i<4;++i)v|=static_cast<std::uint32_t>(static_cast<std::uint8_t>(d[i]))<<(8*i);return v; }
LootCodecError valid_request(const LootRequest& v) noexcept { if(!v.entity_id)return LootCodecError::InvalidEntity;if(!v.loot_id)return LootCodecError::InvalidLootId;if(!v.transaction_id)return LootCodecError::InvalidTransactionId;if(!v.amount)return LootCodecError::InvalidAmount;return LootCodecError::None; }
bool valid_result(LootResultCode c) noexcept { return static_cast<std::uint8_t>(c)<=static_cast<std::uint8_t>(LootResultCode::InvalidRequest); }
}}
namespace kraken::net {
LootCodecError encode_loot_request(const LootRequest& v, MutableByteView o) noexcept { if(o.size()<kLootRequestWireSize)return LootCodecError::OutputTooSmall;auto e=valid_request(v);if(!loot_codec_succeeded(e))return e;auto*d=o.data();put32(d,kLootRequestWireMagic);put16(d+4,kLootWireVersion);put16(d+6,0);put32(d+8,v.entity_id);put32(d+12,v.loot_id);put32(d+16,v.transaction_id);put32(d+20,v.amount);return LootCodecError::None; }
LootCodecError decode_loot_request(ByteView i,LootRequest& o) noexcept {if(i.size()!=kLootRequestWireSize)return LootCodecError::InputSizeMismatch;auto*d=i.data();if(get32(d)!=kLootRequestWireMagic)return LootCodecError::BadMagic;if(get16(d+4)!=kLootWireVersion)return LootCodecError::BadVersion;if(get16(d+6))return LootCodecError::BadFlags;LootRequest v{get32(d+8),get32(d+12),get32(d+16),get32(d+20)};auto e=valid_request(v);if(!loot_codec_succeeded(e))return e;o=v;return e;}
LootCodecError encode_loot_result(const LootResult& v,MutableByteView o) noexcept {if(o.size()<kLootResultWireSize)return LootCodecError::OutputTooSmall;if(!v.transaction_id)return LootCodecError::InvalidTransactionId;if(!v.loot_id)return LootCodecError::InvalidLootId;if(!valid_result(v.code))return LootCodecError::InvalidResultCode;auto*d=o.data();put32(d,kLootResultWireMagic);put16(d+4,kLootWireVersion);d[6]=static_cast<Byte>(v.code);d[7]=Byte{};put32(d+8,v.transaction_id);put32(d+12,v.loot_id);put32(d+16,static_cast<std::uint32_t>(v.resource_id));put32(d+20,v.granted_amount);put32(d+24,v.remaining_amount);put32(d+28,0);return LootCodecError::None;}
LootCodecError decode_loot_result(ByteView i,LootResult& o) noexcept {if(i.size()!=kLootResultWireSize)return LootCodecError::InputSizeMismatch;auto*d=i.data();if(get32(d)!=kLootResultWireMagic)return LootCodecError::BadMagic;if(get16(d+4)!=kLootWireVersion)return LootCodecError::BadVersion;if(d[7]!=Byte{}||get32(d+28))return LootCodecError::BadFlags;auto c=static_cast<LootResultCode>(static_cast<std::uint8_t>(d[6]));if(!valid_result(c))return LootCodecError::InvalidResultCode;LootResult v{get32(d+8),get32(d+12),static_cast<std::int32_t>(get32(d+16)),get32(d+20),get32(d+24),c};if(!v.transaction_id)return LootCodecError::InvalidTransactionId;if(!v.loot_id)return LootCodecError::InvalidLootId;o=v;return LootCodecError::None;}
}
