
namespace m3d {
    enum class EventType {
        // Native enum
        EV_MESSAGE                      = 0x00,
        EV_APP_QUIT                     = 0x01,
        EV_ACTIVATE_APP                 = 0x02,
        EV_CHANGE_DISPLAY_MODE          = 0x03,
        EV_DISPLAY_CHANGED              = 0x04,
        EV_LOOSING_FOCUS                = 0x05,
        EV_OBTAINED_FOCUS               = 0x06,
        EV_KEY_DOWN                     = 0x07,
        EV_KEY_UP                       = 0x08,
        EV_MOUSE_MOVE                   = 0x09,
        EV_MOUSE_LBTN                   = 0x0A,
        EV_MOUSE_RBTN                   = 0x0B,
        EV_MOUSE_MBTN                   = 0x0C,
        EV_MOUSE_DBLCLICK               = 0x0D,
        EV_MOUSE_CLICK                  = 0x0E,
        EV_MOUSE_WHEEL                  = 0x0F,
        EV_JOYSTICK_BTN0                = 0x10,
        EV_JOYSTICK_BTN1                = 0x11,
        EV_JOYSTICK_BTN2                = 0x12,
        EV_JOYSTICK_BTN3                = 0x13,
        EV_JOYSTICK_BTN4                = 0x14,
        EV_JOYSTICK_BTN5                = 0x15,
        EV_JOYSTICK_BTN6                = 0x16,
        EV_JOYSTICK_BTN7                = 0x17,
        EV_JOYSTICK_BTN8                = 0x18,
        EV_JOYSTICK_BTN9                = 0x19,
        EV_JOYSTICK_X_AXIS_PLUS         = 0x1A,
        EV_JOYSTICK_X_AXIS_MINUS        = 0x1B,
        EV_JOYSTICK_Y_AXIS_PLUS         = 0x1C,
        EV_JOYSTICK_Y_AXIS_MINUS        = 0x1D,
        EV_JOYSTICK_Z_AXIS_PLUS         = 0x1E,
        EV_JOYSTICK_Z_AXIS_MINUS        = 0x1F,
        EV_JOYSTICK_Z_ROT_PLUS          = 0x20,
        EV_JOYSTICK_Z_ROT_MINUS         = 0x21,
        EV_JOYSTICK_S0_PLUS             = 0x22,
        EV_JOYSTICK_S0_MINUS            = 0x23,
        EV_JOYSTICK_S1_PLUS             = 0x24,
        EV_JOYSTICK_S1_MINUS            = 0x25,
        EV_MOUSE_MOVE_ON_UI             = 0x26,
        EV_UI_CLOSE_MODAL_WND           = 0x27,
        EV_UI_NOTIFY_WND                = 0x28,
        EV_UI_MODAL_WND_IS_CLOSED       = 0x29,
        EV_UI_END_WND_ANIMATION         = 0x2A,
        EV_UI_STOP_ALL_WND_ANIMATIONS   = 0x2B,
        EV_INSERT_CREATED_TOOLTIP       = 0x2C,
        EV_REMOVE_TOOLTIP               = 0x2D,
        EV_KEYBINDINGS_CHANGED          = 0x2E,
        EV_UI_COMBO_OPENED              = 0x2F,
        EV_UI_COMBO_CLOSED              = 0x30,
        EV_USER                         = 0x10000,
        // Suggested
        // CMiracle3d::OnEvent
        EV_USER_MESSAGE_BOX             = 0x103F6,
        UNKNOWN_0                       = 0x10072,
        EV_USER_CHANGE_PROFILE          = 0x1008e,
        EV_USER_NEXTMAP                 = 0x103f5,
        EV_USER_SET_MUSIC_TYPE          = 0x103FB,
        EV_USER_PLAY_SOUND_MESSAGE      = 0x10400,
    };
};